discussion/discussion/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

discussion/todolist/urls.py
from django.urls import path
from . import views

# Adding a namespace to this urls.py helps django distinguish this set of routes from other urls.py files in other packages
app_name = 'todolist'
urlpatterns = [
    path('', views.index, name="index"),
    # localhost:8000/todolist/1
    path('<int:todoitem_id>/', views.todoitem, name="viewtodoitem"),
    path('register/', views.register, name="register"),
    path('change-password/', views.change_password, name="change_password"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('add_task/', views.add_task, name="add_task"),
    path('<int:todoitem_id>/edit', views.update_task, name="update_task"),
    path('<int:todoitem_id>/delete', views.delete_task, name="delete_task"),
    path('add_event/', views.add_event, name="add_event"),
    path('<int:event_id>/event', views.view_event, name="view_event"),
    path('update_profile/', views.update_profile, name="update_profile"),
    path('register_user/', views.register_user, name="register_user")
]

discussion/todolist/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class ToDoItem(models.Model):
	# CharField = String value
	# DateTimeField = Datetime datatype
	task_name = models.CharField(max_length = 50)
	description = models.CharField(max_length = 200)
	status = models.CharField(max_length = 50, default = "Pending")
	date_created = models.DateTimeField("Date Created")
	# Adding a user_id to the ToDoItem table, which is a foreign key connected to the Users table.
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class MyEvents(models.Model):
	event_name = models.CharField(max_length = 50)
	description = models.CharField(max_length = 200)
	status = models.CharField(max_length = 50, default="Pending")
	event_date = models.DateField(default=datetime.date.today)
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

discussion/todolist/forms.py
from django.core.exceptions import ValidationError
from django.utils import timezone
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label="Username", max_length=20)
	password = forms.CharField(label="Password", max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	status = forms.CharField(label="Status", max_length=50)

def validate_event_date(value):
	if value < timezone.now().date():
		raise ValidationError("Event date can not be in the past")

class EventForm(forms.Form):
	event_name = forms.CharField(label="Event Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	event_date = forms.DateField(label="Event Date", validators=[validate_event_date])

class UpdateProfileForm(forms.Form):
	first_name = forms.CharField(label="First Name", max_length=50)
	last_name = forms.CharField(label="Last Name", max_length=50)
	password = forms.CharField(label="Password", max_length=50, required=False)
	new_password = forms.CharField(label="New Password", max_length=50, required=False)

class RegisterForm(forms.Form):
	first_name = forms.CharField(label="First Name", max_length=50)
	last_name = forms.CharField(label="Last Name", max_length=50)
	email = forms.CharField(label="Email", max_length=50)
	username = forms.CharField(label="Username", max_length=50)
	password = forms.CharField(label="Password", max_length=50)

discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

# We import the built-in 'User' model to be able to do operations to the built-in User's table from Django.
from django.contrib.auth.models import User
from .models import ToDoItem, MyEvents
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, EventForm, UpdateProfileForm, RegisterForm

# Create your views here.
def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	events_list = MyEvents.objects.filter(user_id=request.user.id)

	template = loader.get_template('todolist/index.html')
	context = {
		'todoitem_list': todoitem_list,
		'events_list': events_list,
		'user': request.user
	}

	return HttpResponse(template.render(context, request))

	# You can also render a template using this way
	# return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	# 'model_to_dict' function translates a data model into a python dictionary (object). This is so that we can use the data as a regular object/dictionary.
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

	# ACTIVITY
	# 1. Create a todoitem template
	# 2. In the template, show the 'task_name' and 'description', 'status' of the todo item. (each enclosed in an HTML tag)
	# 3. At the end of the template, create an anchor tag that will return the user to the 'index' page

def register(request):
	users = User.objects.all()
	is_user_registered = False

	# Loops through each existing user and checks if they already exist in the table
	for individual_user in users:
		if individual_user.username == "johndoe":
			is_user_registered = True
			break

	# The context 'is_user_registered' is put after the for loop in order for it to get the updated value if 'for' loop above equals to True.
	context = {
		"is_user_registered": is_user_registered
	}

	if is_user_registered == False:
		# 1. Creating a new instance of the User model
		user = User()

		# 2. Assign data values to each property of the model.
		user.username = "johndoe"
		user.first_name = "John"
		user.last_name = "Doe"
		user.email = "john@mail.com"
		user.set_password("john1234")
		user.is_staff = False
		user.is_active = True

		# 3. Save the new instance of a user into the database.
		user.save()

		# The context will be the data to be passed to the template
		context = {
			"first_name": user.first_name,
			"last_name": user.last_name
		}

	return render(request, "todolist/register.html", context)

def change_password(request):
	is_user_authenticated = False

	user = authenticate(username = "johndoe", password = "john1234")
	# print(user)

	if user is not None:
		authenticated_user = User.objects.get(username = "johndoe")

		authenticated_user.set_password("johndoe1")
		authenticated_user.save()

		is_user_authenticated = True

	context = {
		"is_user_authenticated": is_user_authenticated
	}

	return render(request, 'todolist/change_password.html', context)

def login_view(request):
	context = {}

	if request.method == 'POST':
		# request.POST contains all the fields coming from the login.html form
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			# if you use LoginForm() without passing any data, it will just return the properties 'username' and 'password' without any data/value
			form = LoginForm()

		else:
			# we use the 'form.cleaned_data[]' to get the properties that we need from the form
			# we can use the properties declared in the forms.py within the LoginForm class to get their values
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = authenticate(username = username, password = password)

			context = {
				"username": username,
				"password": password
			}

			if user is not None:
				# The 'Login' function saves the user's ID in Django's session. The request will be the one that handles the user's data and we can access the user by using 'request.user'
				login(request, user)
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}

	return render(request, 'todolist/login.html', context)

def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name = task_name)

			if not duplicates:
				ToDoItem.objects.create(
					task_name = task_name,
					description = description,
					date_created = timezone.now(),
					user_id = request.user.id # ID of the logged in user
				)

				return redirect('todolist:index')

			else:
				context = {
					"error": True
				}

	return render(request, 'todolist/add_task.html', context)

def update_task(request, todoitem_id):
	# Returns a queryset
    todoitem = ToDoItem.objects.filter(pk=todoitem_id)

    context = {
        "user": request.user,
        "todoitem_id": todoitem_id,
        # Accessing the first element is necessary because the "ToDoItem.objects.filter()" method returns a queryset
        "task_name": todoitem[0].task_name,
        "description": todoitem[0].description,
        "status": todoitem[0].status
    }

    if request.method == 'POST':

        form = UpdateTaskForm(request.POST)

        if form.is_valid() == False:

            form = UpdateTaskForm()

        else:
            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']
            
            if todoitem:

                todoitem[0].task_name = task_name
                todoitem[0].description = description
                todoitem[0].status = status

                todoitem[0].save()
                return redirect("todolist:index")

            else:

                context = {
                    "error": True
                }

    return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id)
	todoitem.delete()

	return redirect('todolist:index')

def add_event(request):

	context = {}

	if request.method == 'POST':
		form = EventForm(request.POST)

		if form.is_valid() == False:
			form = EventForm()
			context = {
				"error": "Event date cannot be in the past"
			}

		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			event_date = form.cleaned_data['event_date']

			duplicates = MyEvents.objects.filter(event_name = event_name)

			if not duplicates:
				MyEvents.objects.create(
					event_name = event_name,
					description = description,
					event_date = event_date,
					user_id = request.user.id
				)

				return redirect('todolist:index')

			else:
				context = {
					"error": "Duplicate event found"
				}

	return render(request, 'todolist/add_event.html', context)

def view_event(request, event_id):

	event = get_object_or_404(MyEvents, pk=event_id)

	return render(request, "todolist/view_event.html", model_to_dict(event))

def update_profile(request):
	user = User.objects.filter(pk=request.user.id)

	context = {
		"first_name": user[0].first_name,
		"last_name": user[0].last_name,
		"password": user[0].password,
		"is_user_authenticated": True
	}

	if request.method == 'POST':
		form = UpdateProfileForm(request.POST)

		if form.is_valid() == False:
			UpdateProfileForm()

		else:
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			old_password = form.cleaned_data['password']
			new_password = form.cleaned_data['new_password']

			if user:
				user[0].first_name = first_name


				user[0].last_name = last_name

				if old_password:
					if user[0].check_password(old_password):
						if new_password:
							user[0].set_password(new_password)
						else:
							context = {
								"error": "Please provide a new password"
							}
					else:
						context = {
							"error": "Old password did not match, try again"
						}

				user[0].save()
				return render(request, "todolist/change_password.html", context)
			else:
				context = {
					"is_user_authenticated": False
				}

	return render(request, "todolist/profile.html", context)

def register_user(request):
	context = {}

	if request.method == 'POST':
		form = RegisterForm(request.POST)

		if form.is_valid() == False:
			RegisterForm()

		else:
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			duplicates = User.objects.filter(username = username)

			if not duplicates:
				user = User()

				user.username = username
				user.first_name = first_name
				user.last_name = last_name
				user.email = email
				user.set_password(password)
				user.is_staff = False
				user.is_active = True

				user.save()

				context = {
					"first_name": first_name,
					"last_name": last_name,
					"is_user_registered": False
				}

				return render(request, 'todolist/register.html', context)

			else:
				context = {
					"is_user_registered": True
				}
				return render(request, 'todolist/register.html', context)

	return render(request, 'todolist/register_form.html', context)

discussion/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}
{% block title %}Add a new event{% endblock %}
{% load static %}

{% block content %}
	{% if user.is_anonymous == False %}
		<div class="container my-5 py-5">
			<div class="row my-5 py-5 rounded card-shadow">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Add An Event</h1>
					{% if error %}
						<p class="text-danger">{{ error }}</p>
					{% endif %}
					<form action="{% url 'todolist:add_event' %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
							<label for="event_name">Event Name:</label>
							<input 
								type="text" 
								class="form-control" 
								id="event_name"
								name="event_name"
								value="{{ event_name }}" 
								maxlength="50"
								required 
							>
						</div>
						<div class="mb-3">
							<label for="description">Description:</label>
							<input 
								type="text"
								class="form-control"
								id="description"
								name="description"
								value="{{ description }}"
								required 
							>
						</div>
						<div class="mb-3">
							<label for="event_date">Date:</label>
							<input 
								type="date"
								class="form-control"
								id="event_date"
								name="event_date"
								value="{{ event_date }}"
								required 
							>
						</div>
						<div class="text-center">
							<input type="submit" class="btn btn-success w-100" value="Create Event">
						</div>
					</form>
				</div>
			</div>
		</div>
	{% else %}
		<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5">
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<img src="{% static 'gif/401 Error Unauthorized.gif' %}" alt="401_unauthorized" class="w-50">
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		</div>
	{% endif %}
{% endblock %}

discussion/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}
{% block title %}Add a new Task{% endblock %}
{% load static %}

{% block content %}
	{% if user.is_anonymous == False %}
		<div class="container my-5 py-5">
			<div class="row my-5 py-5 rounded card-shadow">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Add a Task</h1>
					{% if error == True %}
						<p class="text-danger">Duplicate task found</p>
					{% endif %}
					<form action="{% url 'todolist:add_task' %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
							<label for="task_name">Task Name:</label>
							<input 
								type="text" 
								class="form-control" 
								id="task_name"
								name="task_name"
								value="{{ task_name }}" 
								maxlength="50"
								required 
							>
						</div>
						<div class="mb-3">
							<label for="description">Description:</label>
							<input 
								type="text"
								class="form-control"
								id="description"
								name="description"
								value="{{ description }}"
								required 
							>
						</div>
						<div class="text-center">
							<input type="submit" class="btn btn-success w-100" value="Create Task">
						</div>
					</form>
				</div>
			</div>
		</div>
	{% else %}
		<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5">
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<img src="{% static 'gif/401 Error Unauthorized.gif' %}" alt="401_unauthorized" class="w-50">
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		</div>
	{% endif %}
{% endblock %}

discussion/todolist/templates/todolist/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% load static %}

{% block content %}
	{% if todoitem_list or events_list and user.is_anonymous == False %}
		<div class="container my-5 py-5">
			<div class="d-flex flex-column my-5 p-5 rounded card-shadow">
				<h1 class="text-center my-3">Welcome {{ user.first_name }} {{ user.last_name }}!</h1>
				<div class="row">
					<h3 class="text-center my-3">My Tasks</h3>
					<ul class="list-group col-lg-2 offset-lg-5 text-center">
						{% if not todoitem_list %}
							<p class="text-center">No tasks have been created.</p>
						{% else %}
							{% for todoitem in todoitem_list %}
								<a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
									<li class="list-group-item">{{ todoitem.task_name }}</li>
								</a>
							{% endfor %}
						{% endif %}
					</ul>
					<h3 class="text-center my-3">My Events</h3>
					<ul class="list-group col-lg-2 offset-lg-5 text-center">
						{% if not events_list %}
							<p class="text-center">No events have been created.</p>
						{% else %}
							{% for myevents in events_list %}
								<a href="{% url 'todolist:view_event' myevents.id %}" class="text-decoration-none">
									<li class="list-group-item">{{ myevents.event_name }}</li>
								</a>
							{% endfor %}
						{% endif %}
					</ul>
				</div>
			</div>
		</div>	    
	{% elif user.is_anonymous == True %}
		<div class="d-flex flex-column justify-content-center align-items-center h-auto my-5 py-5">
			<h1 class="text-center my-3"><span class="title">Create your <span class="highlight">task</span></span> and <span class="title">schedule <span class="highlight">events</span></span></h1>
			<div class="f-flex flex-column my-3">
				<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
				<p class="text-center">Don't have an account yet? Sign up <a href="{% url 'todolist:register_user' %}">here</a></p>
			</div>
		</div>
	{% else %}
		<div class="container my-5 py-5">
			<h1 class="text-center">Start by creating a task or event</h1>
		</div>
	{% endif %}
{% endblock %}

discussion/todolist/templates/todolist/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% load static %}

{% block content %}
	<div class="container my-5 py-5">
		<div class="row my-5 py-5">
			<div class="col-6 offset-3">
				{% if user.is_anonymous == True %}
					<h1 class="text-center my-4">Login</h1>
					<form action="{% url 'todolist:login' %}" method="post">
						<!-- 
							CSRF Token (Cross site request forgeries) 
							- For making sure that the form request is coming from the same django project. If not, django will block the request.

							Note: ALL forms in django needs a csrf_token.
						-->
						{% csrf_token %}
						
						<div class="mb-3">
							<label for="username">Username:</label>
							<input type="text" class="form-control" id="username" maxlength="20" name="username" value="{{ username }}" required>
						</div>
						<div class="mb-3">
							<label for="password">Password:</label>
							<input type="password" class="form-control" id="password" maxlength="20" name="password" value="{{ password }}" required>
						</div>
						<div class="text-center">
							<input type="submit" class="btn btn-primary w-100" value="login">
						</div>
					</form>
				{% else %}
					<div class="d-flex flex-column justify-content-center align-items-center">
						<h1 class="text-center my-3">You don't have permission to access this resource</h1>
						<img src="{% static 'gif/403 Error Forbidden.gif' %}" alt="401_unauthorized">
						<p class="text-center">Return to <a href="{% url 'todolist:index' %}">index</a></p>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

discussion/todolist/templates/todolist/profile.html
{% extends 'base.html' %}
{% block title %}Update profile{% endblock %}
{% load static %}

{% block content %}
	{% if user.is_anonymous == False %}
		<div class="container my-5 py-5">
			<div class="row my-5 py-5 rounded card-shadow">
				<div class="col-6 offset-3">
					{% if is_user_authenticated == False%}
						<h1>Something went wrong</h1>
						<p>Please contact your administrator</p>

						<a href="{% url 'todolist:index' %}">Back to index page</a>
					{% endif %}
					<h1 class="text-center my-3">Profile</h1>
					<form action="{% url 'todolist:update_profile' %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
							<label for="first_name">First name:</label>
							<input 
								type="text" 
								class="form-control" 
								id="first_name"
								name="first_name"
								value="{{ first_name }}" 
								maxlength="50"
								required 
							>
						</div>
						<div class="mb-3">
							<label for="last_name">Last name:</label>
							<input 
								type="text"
								class="form-control"
								id="last_name"
								name="last_name"
								value="{{ last_name }}"
								required 
							>
						</div>
						<h4 class="text-center mt-4">Change password</h4>
						<div class="mb-3">
							<label for="password">Current password:</label>
							<input 
								type="password"
								class="form-control"
								id="password"
								name="password"
							>
						</div>
						<div class="mb-3">
							<label for="new_password">Confirm new password:</label>
							<input 
								type="password"
								class="form-control"
								id="new_password"
								name="new_password"
							>
						</div>
						<div class="text-center">
							<input type="submit" class="btn btn-success w-100" value="Update">
						</div>
					</form>
				</div>
			</div>
		</div>
	{% else %}
		<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5">
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<img src="{% static 'gif/401 Error Unauthorized.gif' %}" alt="401_unauthorized" class="w-50">
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		</div>
	{% endif %}
{% endblock %}

discussion/todolist/templates/todolist/register_form.html
{% extends 'base.html' %}
{% block title %}Sign up{% endblock %}
{% load static %}

{% block content %}
	{% if user.is_anonymous == True %}
		<div class="container my-5 py-5">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Sign up</h1>
					<form action="{% url 'todolist:register_user' %}" method="post">
						{% csrf_token %}

						<div class="row">
							<div class="mb-3 col-6">
								<label for="first_name">First name:</label>
								<input 
									type="text" 
									class="form-control" 
									id="first_name"
									name="first_name" 
									maxlength="50"
									required 
								>
							</div>
							<div class="mb-3 col-6">
								<label for="last_name">Last name:</label>
								<input 
									type="text"
									class="form-control"
									id="last_name"
									name="last_name"
									required 
								>
							</div>
						</div>
						<div class="mb-3">
							<label for="email">Email address:</label>
							<input 
								type="text"
								class="form-control"
								id="email"
								name="email"
								required 
							>
						</div>
						<div class="row">
							<div class="col-6 mb-3">
								<label for="username">Username:</label>
								<input 
									type="text"
									class="form-control"
									id="username"
									name="username"
									required
								>
							</div>
							<div class="col-6 mb-3">
								<label for="password">Password:</label>
								<input 
									type="password"
									class="form-control"
									id="password"
									name="password"
									required
								>
							</div>
						</div>
						<div class="text-center">
							<input type="submit" class="btn btn-primary w-100" value="Submit">
						</div>
					</form>
				</div>
			</div>
		</div>
	{% else %}
		<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5">
			<h1 class="text-center my-3">You don't have permission to access this resource</h1>
			<img src="{% static 'gif/403 Error Forbidden.gif' %}" alt="401_unauthorized" class="w-50">
			<p class="text-center">Return to <a href="{% url 'todolist:index' %}">index</a></p>
		</div>
	{% endif %}
{% endblock %}

discussion/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}
{% block title %}Task details{% endblock %}
{% load static %}

{% block content %}
	{% if user.is_anonymous == True %}
		<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5">
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<img src="{% static 'gif/401 Error Unauthorized.gif' %}" alt="401_unauthorized" class="w-50">
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		</div>
	{% else %}
		<div class="container my-5 py-5">
			<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5 card-shadow rounded">
				<div class="d-flex gap-4 my-3">
					<h1 class="align-self-center task-name"><i class='bx bx-task icons'></i>{{ task_name }}</h1>
					<div class="d-flex flex-column gap-1 mx-5">
						<h4><i class='bx bx-detail icons'></i> Description</h4>
						<p>{{ description }}</p>
						<h4><i class='bx bx-check-square icons'></i> Status</h4>
						<p>{{ status }}</p>
						<h4><i class='bx bx-calendar icons'></i> Date created</h4>
						<p>{{ date_created }}</p>
					</div>
				</div>

				<div class="d-flex justify-content-center gap-2">
					<button class="btn btn-primary mx-1 text-decoration-none">
						<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none"><i class='bx bx-edit icons'></i> Edit task</a>
					</button>
					<button class="btn btn-danger mx-1 text-decoration-none">
						<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none"><i class='bx bx-trash icons'></i> Delete task</a>
					</button>
					<button class="btn btn-success mx-1 text-decoration-none">
						<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none"><i class='bx bx-arrow-back icons'></i> Back to index page</a>
					</button>
				</div>
			</div>
		</div>
	{% endif %}
{% endblock %}

discussion/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}
{% block title %}Update Task{% endblock %}
{% load static %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container my-5 py-5">
		<div class="row my-5 py-5 rounded card-shadow">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">Task not found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
					    <label for="task_name">Task Name: </label>
					    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="description">Description: </label>
					    <textarea class="form-control" name="description" required>{{ description }}</textarea>
					</div>

					<div class="mb-3">
					    <label for="status">Status: </label>
					    <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success w-100" type="submit" value="Update Task">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
	<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5">
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<img src="{% static 'gif/401 Error Unauthorized.gif' %}" alt="401_unauthorized" class="w-50">
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	</div>
	{% endif %}
{% endblock %}

discussion/todolist/templates/todolist/view_event.html
{% extends 'base.html' %}
{% block title %}Task details{% endblock %}
{% load static %}

{% block content %}
	{% if user.is_anonymous == True %}
		<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5">
			<h1 class="text-center my-3">You are not authorized to access this page.</h1>
			<img src="{% static 'gif/401 Error Unauthorized.gif' %}" alt="401_unauthorized" class="w-50">
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
		</div>
	{% else %}
		<div class="container my-5 py-5">
			<div class="d-flex flex-column justify-content-center align-items-center my-5 py-5 rounded card-shadow">
				<div class="d-flex gap-4 my-3">
					<h1 class="align-self-center event-name"><i class='bx bx-calendar-event icons'></i> {{ event_name }}</h1>
					<div class="d-flex flex-column gap-1 mx-5">
						<h3><i class='bx bx-detail icons'></i> Description</h3>
						<p>{{ description }}</p>
						<h3><i class='bx bx-check-square icons'></i> Status</h3>
						<p>{{ status }}</p>
						<h3><i class='bx bx-calendar icons'></i> Date</h3>
						<p>{{ event_date }}</p>
					</div>			
				</div>
			
				<button class="btn btn-success mx-1 text-decoration-none">
					<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none"><i class='bx bx-arrow-back icons'></i> Back to Events</a>
				</button>
			</div>
		</div>
	{% endif %}
{% endblock %}